import type { Metadata } from 'next'
import './globals.css'
import { roboto } from './fonts'

import Header from '@/components/ui/Header'
import { Footer } from '@/components/ui/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antiliased`}>
        <Header title={metadata.title} />
        {children}
        <Footer />
      </body>
  
    </html>
  )
}
